spring.application.name: run-us
spring.profiles.active: local

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update

---
spring.config.activate.on-profile: prod
