spring.application.name: run-us
spring.profiles.active: local

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true

  threads:
    virtual:
      enabled: false

server:
  tomcat:
    mbeanregistry:
      enabled: true # 톰캣 메트릭 모두 활성화

app:
  api:
    allow-origins: ${ALLOW_ORIGINS}
  auth:
    token:
      access:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
        secret-key: ${ACCESS_TOKEN_SECRET_KEY}
      refresh:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
        secret-key: ${REFRESH_TOKEN_SECRET_KEY}
  default-zone-offset: +09:00

oauth:
  apple:
    base-auth-url: https://appleid.apple.com/auth
    client_id: ${APPLE_CLIENT_ID}
    key_id: ${APPLE_KEY_ID}
    team_id: ${APPLE_TEAM_ID}

weather:
  openweathermap:
    url: https://api.openweathermap.org
    api-key: ${OPENWEATHER_API_KEY}
  weatherapicom:
    url: https://api.weatherapi.com
    api-key: ${WEATHERAPICOM_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, circuitbreakers
  health:
    circuitbreakers:
      enabled: true

---
spring.config.activate.on-profile: local

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL_SLOW: INFO
    org.hibernate.stat: DEBUG

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    properties:
      hibernate:
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300

logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL_SLOW: INFO
