spring.application.name: run-us
spring.profiles.active: local

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  api:
    allow-origins: ${ALLOW_ORIGINS}
  auth:
    token:
      access:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
        secret-key: ${ACCESS_TOKEN_SECRET_KEY}
  default-zone-offset: +09:00

oauth:
  apple:
    public-key-url: https://appleid.apple.com/auth

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: prod
