spring.application.name: run-us
spring.profiles.active: local

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

app:
  api:
    allow-origins: ${ALLOW_ORIGINS}
  auth:
    token:
      access:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
        secret-key: ${ACCESS_TOKEN_SECRET_KEY}

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update

---
spring.config.activate.on-profile: prod
