-- crate challenge table
CREATE TABLE challenge
(
    id              bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar NOT NULL,
    expected_time   integer NOT NULL,
    challenge_type  varchar(100) NOT NULL,
    image_url       varchar NOT NULL
);

-- add challenge table comment
COMMENT
ON TABLE challenge IS 'challenge 테이블(서비스에서 정한 챌린지 데이터)';
COMMENT
ON COLUMN challenge.name IS '챌린지 이름(ex. 3km 달리기 등)';
COMMENT
ON COLUMN challenge.expected_time IS '챌린지 수행 예상 소요 시간(초 단위, 거리와 관련 챌린지면 평균 페이스를 8분 기준으로 입력, 페이스 관련 챌린지면 0으로 입력)';
COMMENT
ON COLUMN challenge.challenge_type IS '챌린지 타입{DEFEAT_YESTERDAY:어제의 기록을 이기는 챌린지, TODAY:오늘의 챌린지, DISTANCE_IN_TIME:지정 시간 안에 일정 거리를 달리는 챌린지(1km 6분 이내로 달리기)}';
COMMENT
ON COLUMN challenge.image_url IS '챌린지 이미지 url';

-- crate challenge_goal_condition table
CREATE TABLE challenge_goal_condition
(
    id                  bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id        bigint  NOT NULL
        CONSTRAINT fk_challenge_goal_condition_challenge_id REFERENCES challenge,
    goal_type           varchar(100) NOT NULL,
    goal_value          integer NOT NULL,
    comparison_type     varchar(100) NOT NULL
);

-- add challenge_goal_condition table comment
COMMENT
ON TABLE challenge_goal_condition IS '챌린지 목표 조건 테이블(challenge 테이블의 챌린지에 대한 목표 조건 데이터, 목표 조건이 하나의 챌린지에 여러개 존재할 수 도 있음)';
COMMENT
ON COLUMN challenge_goal_condition.challenge_id IS '목표 조건에 해당하는 챌린지 id';
COMMENT
ON COLUMN challenge_goal_condition.goal_type IS '목표 타입(TIME, DISTANCE, PACE)';
COMMENT
ON COLUMN challenge_goal_condition.goal_value IS '목표 값(DISTANCE:미터 단위, TIME:초 단위, PACE: 초 단위)';
COMMENT
ON COLUMN challenge_goal_condition.comparison_type IS '비교 타입(GREATER_THAN_OR_EQUAL_TO:크거나 같다, LESS_THAN_OR_EQUAL_TO:작거나 같다)';
